# -*- coding: utf-8 -*-
"""Pipeline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kY4i_00ObEEkf1u-3LLd2TkyyRhFAYUA
"""

import numpy as np
import librosa

def extract_features(file_path):
    """
    Loads an individual audio file, standardizes sample rate, normalizes
    duration to 4 seconds, and extracts a normalized Log-Mel Spectrogram matrix.
    """
    TARGET_SR = 22050          # Uniform sampling rate
    DURATION = 4                # Fixed target clip length in seconds
    TOTAL_SAMPLES = TARGET_SR * DURATION  # 88,200 audio points
    N_MELS = 128                # Mel-frequency frequency bands (height)

    try:
        # 1. Load signal and enforce target sample rate
        y, sr = librosa.load(file_path, sr=TARGET_SR)

        # 2. Standardize duration (zero-pad short clips, truncate long clips)
        y_fixed = librosa.util.fix_length(y, size=TOTAL_SAMPLES)

        # 3. Transform 1D signal to a 2D Mel-Spectrogram matrix
        mel_spect = librosa.feature.melspectrogram(y=y_fixed, sr=TARGET_SR, n_mels=N_MELS)

        # 4. Scale power values logarithmically to Decibels (dB)
        mel_db = librosa.power_to_db(mel_spect, ref=np.max)

        return mel_db

    except Exception as e:
        print(f"Pipeline error parsing audio track at {file_path}: {e}")
        return None