# -*- coding: utf-8 -*-
"""predict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0J_EtMNnt4BhlVB1zgS8FWvKq_bjSrB
"""

import sys
import torch
import torch.nn.functional as F
from pipeline import extract_features
from model import AudioCNN

# Map output indices directly to dataset class tags
CLASS_MAP = [
    'Air Conditioner', 'Car Horn', 'Children Playing', 'Dog Bark',
    'Drilling', 'Engine Idling', 'Gun Shot', 'Jackhammer', 'Siren', 'Street Music'
]

def run_inference(audio_file_path, model_weights_path='audio_cnn_baseline.pth'):
    # 1. Select operational hardware
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # 2. Extract standardized feature matrix
    print(f"Preprocessing target file: {audio_file_path}")
    features = extract_features(audio_file_path)

    if features is None:
        print("Failed to process audio sequence.")
        return

    # 3. Shape features for PyTorch 2D CNN format: (Batch=1, Channel=1, H=128, W=173)
    tensor_input = torch.tensor(features, dtype=torch.float32).unsqueeze(0).unsqueeze(0).to(device)

    # 4. Initialize architecture and inject trained state weights
    model = AudioCNN().to(device)
    try:
        model.load_state_dict(torch.load(model_weights_path, map_location=device))
        model.eval()  # Freeze BatchNorm and Dropout behaviors
    except FileNotFoundError:
        print(f"Error: Weights file '{model_weights_path}' not found in runtime workspace.")
        return

    # 5. Execute core computation
    with torch.no_grad():
        logits = model(tensor_input)
        probabilities = F.softmax(logits, dim=1)
        confidence, target_class_idx = torch.max(probabilities, 1)

    # 6. Report outputs
    predicted_label = CLASS_MAP[target_class_idx.item()]
    confidence_score = confidence.item() * 100

    print("\n--- Model Inference Result ---")
    print(f"Predicted Class : {predicted_label}")
    print(f"Model Confidence: {confidence_score:.2f}%")

if __name__ == '__main__':
    # Usage: python predict.py path_to_file.wav
    if len(sys.argv) > 1:
        target_audio = sys.argv[1]
        run_inference(target_audio)
    else:
        print("Usage Error: Please supply a track path. Example: python predict.py sample.wav")